import {Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
const geistSans = Roboto({
  variable: "Roboto",
  subsets: ["sans-serif"],
});


export const metadata = {
  title: "capitoCoding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased bg-gray-900`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
